[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "executor"
description = "Abstraction layer for quantum circuits and operators across multiple backends."
readme = "README.md"
authors = [
    {name = "David Kreplin", email = "david.kreplin@ipa.fraunhofer.de"},
    {name = "Moritz Willmann", email = "moritz.willmann@ipa.fraunhofer.de"},
    {name = "Jan Schnabel", email = "jan.schnabel@ipa.fraunhofer.de"},
    {name = "Manuel Hagelüken", email = "manuel.hagelueken@ipa.fraunhofer.de"},
    {name = "Marco Roth", email = "marco.roth@ipa.fraunhofer.de"},
]
maintainers = [
    {name = "David Kreplin", email = "david.kreplin@ipa.fraunhofer.de"},
    {name = "Moritz Willmann", email = "moritz.willmann@ipa.fraunhofer.de"},
]
license = {file = "LICENSE.txt"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
keywords = ["quantum", "circuit", "executor", "pennylane", "qiskit", "qulacs"]
dependencies = [
    "dill>=0.3.4",
    "mapomatic>=0.10.0",
    "numpy>=1.20",
    "qiskit>=1.0.0",
    "sympy>=1.8",
]
requires-python = ">=3.10"
dynamic = ["version"]

[project.optional-dependencies]
pennylane = ["pennylane>=0.34.0"]
qulacs = ["qulacs>=0.6.4.1"]
qiskit-full = ["qiskit-aer>=0.12.0", "qiskit-ibm-runtime>=0.18.0"]
pauli_propagation = []
all = [
    "pennylane>=0.34.0",
    "qulacs>=0.6.4.1",
    "qiskit-aer>=0.12.0",
    "qiskit-ibm-runtime>=0.18.0",
]

[project.entry-points."executor.backends"]
pennylane = "executor.pennylane:PennyLaneExecutor"
qiskit = "executor.qiskit:QiskitExecutor"
qulacs = "executor.qulacs:QulacsExecutor"
pauli_propagation = "executor.pauli_propagation:PauliPropagationExecutor"

[dependency-groups]
dev = [
    "black[jupyter]",
    "pylint",
    "pytest",
    "nbmake",
]
docs = [
    "sphinx>=7.0",
    "sphinx-autodoc-typehints",
]
examples = [
    "nbmake",
    "jupyter",
    "matplotlib",
    "pylatexenc",
    "qulacsvis>=0.7.6",
    "scikit-learn>=1.7.2",
]

[tool.uv]
managed = true

[tool.hatch.version]
path = "src/executor/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/executor"]

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
line_length = 99

[tool.pylint]
max-line-length = 99

[tool.pylint.main]
extension-pkg-allow-list = [
    "numpy",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "@abstractmethod",
]