name: Documentation check

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  doc_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --all-extras --group docs

      - name: Build documentation
        working-directory: docs/
        run: uv run sphinx-build -b html . _build -W --keep-going
